spring:
  application:
    name: chirp

  datasource:
    url: jdbc:postgresql://localhost:5433/chirp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

  devtools:
    restart:
      exclude: "resources/static/**"